### ISSUE TITLE
用Clion打开draw_cube_texture_compress这个工程出现如下报错，发现是stopwatch.h不是utf-8 with bom格式导致的,用sublime重新保存为with bom就可以了

### ISSUE THREAD

**Issue by kaclok** [ThisisGame/cpp-game-engine-book#11]
cpp-game-engine-book\samples\texture\draw_cube_texture_compress\depends\timetool/stopwatch.h(46): error C2059: 语法错误:“{”
cpp-game-engine-book\samples\texture\draw_cube_texture_compress\depends\timetool/stopwatch.h(46): error C2334: “{”的前面有意外标记；跳过明显的函数体

**Comment by Pierce-Dai** [comment]
我也遇到了这个问题！看到别的地方有人说是文件解码的原因需要utf-8 with bom格式，我还检查了clion的setting是utf-8 with bom格式，非常纳闷，原来需要重新保存，感谢！

**Comment by ThisisGame** [comment]
已修改。
