### ISSUE TITLE
RTTR (rttr::policy::ctor::as_raw_ptr) have a problem

### ISSUE THREAD

**Issue by Cc1xiaoyu** [ThisisGame/cpp-game-engine-book#13]
我运行9.1节的测试程序时，vs2022出现报错main.obj : error LNK2001: 无法解析的外部符号 "public: static struct rttr::detail::as_raw_pointer const rttr::policy::ctor::as_raw_ptr" (?as_raw_ptr@ctor@policy@rttr@@2Uas_raw_pointer@detail@3@B)，

**Comment by ThisisGame** [comment]
直接使用源码编译ok了
