### ISSUE TITLE
章节打不开咧。

### ISSUE THREAD

**Issue by MENGJIANGTAO** [ThisisGame/cpp-game-engine-book#7]
你好，在线阅读时，第14章，第16章打开报如下错误。

An error occurred.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the [error log](http://nginx.org/r/error_log) for details.

We have articles on troubleshooting issues like [high CPU usage](https://blog.openresty.com/en/lua-cpu-flame-graph/?src=wb) and [large memory usage](https://blog.openresty.com/en/how-or-alloc-mem/) on [our official blog site](https://blog.openresty.com/).

Faithfully yours, [OpenResty](https://openresty.org/).

**Comment by ThisisGame** [comment]
感谢，已经可以了，markdown文件名大小写的问题。

**Comment by MENGJIANGTAO** [comment]
感谢大佬，又可愉快的学习了。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月10日 00:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ThisisGame/cpp-game-engine-book] 章节打不开咧。 (Issue #7) |

感谢，已经可以了，markdown文件名大小写的问题。
