### ISSUE TITLE
error gitbook server 

### ISSUE THREAD

**Issue by sunlighing** [ThisisGame/cpp-game-engine-book#9]
error: error while generating page "23. classic_lighting/23.9 multi_light.md":

Template render error: (F:\cpp-game-engine-book\pages\23. classic_lighting\23.9 multi_light.md) [Line 237, Column 47]
  unexpected token: }}
![image](https://user-images.githubusercontent.com/22463492/199958132-7c7d2858-6b7f-46a7-ad94-96fc7665231e.png)

**Comment by ThisisGame** [comment]
GitBook 对这种双大括号的解析有问题。
在线阅读：https://thisisgame.com.cn/tutorial?book=cpp-game-engine-book&lang=zh&md=23.%20classic_lighting/23.9%20multi_light.md

我在整理目前的网站代码，开源出来 替换掉GitBook。

**Comment by ThisisGame** [comment]
> error: error while generating page "23. classic_lighting/23.9 multi_light.md":
> 
> Template render error: (F:\cpp-game-engine-book\pages\23. classic_lighting\23.9 multi_light.md) [Line 237, Column 47] unexpected token: }} ![image](https://user-images.githubusercontent.com/22463492/199958132-7c7d2858-6b7f-46a7-ad94-96fc7665231e.png)

https://github.com/ThisisGame/thisisgame-web-openresty

试试这个
